version: '27.4'

services:
  mongo-db:
    image: mongo:7.0.16
    restart: always
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      # ME_CONFIG_BASICAUTH: false
    volumes:
      - ./mongo:/data/db
    ports: 
       - 27018:27017
